### PR TITLE
Refactoring: Standardized `python3` project

### PR DESCRIPTION
**Pull request by n3rada**
Hello maintainers, hello @El3ct71k 👋

Your project to interact with an MS SQL database from an attacker's workstation using `impacket` is very interesting and promising for operational exercises.

So I've taken some time out to make this tool a little more standardized in terms of `python` development rules. The libraries have been sorted and, above all, the project can now be installed (once merged) via a simple :
```shell
pipx install 'git+https://github.com/ScorpionesLabs/MSSqlPwner.git'
```

This is the most common use for production applications. It avoids conflicting libraries, etc. I've also added the `prompt_toolkit` module, which renders the pseudo-terminal as a TTY, with history and suggestions from your own modules. Typing `get-chain-links` is now easy.

I hope you'll appreciate this Pull Request

### CODE REVIEW

**Comment by El3ct71k** [comment]
Hi, I'll do some checks and approves it soon once it will pass all the
examples

**Comment by El3ct71k** [comment]
@n3rada can we discuss on discord/mail ?

**Comment by n3rada** [comment]
@El3ct71k of course: n3rada#9522

**Comment by El3ct71k** [comment]
@n3rada sent you friend request on discord

**Comment by n3rada** [comment]
I have no way to save a good screenshot for the `bruteforce` feature. But everything works well. I'll let you handle this case. You still have to add proper version number and so on.

**Comment by n3rada** [comment]
Closes #2

**Pull request merged**
